const axios = require('axios')
const createSlice = require('@reduxjs/toolkit').createSlice

//this method is to create and dispatch async actions. this method accepts action types as first params, then a callback func(which must return a promise) as sec param
//the method (1) generates promise lifecycle action types based on the action type prefix that you pass in, and (2)returns a thunk action creator that will run the promise callback and dispatch the lifecycle actions based on the returned promise.

//(3) then we can listen to the lifecycle action types with a reducer function(using the extra reducer property since the action types were not auto generated by the slice) and perform the necessary state changes
const createAsyncThunk = require('@reduxjs/toolkit').createAsyncThunk

const initialState = {
  loading: false,
  users: [],
  error: ''
}

// Generates pending, fulfilled and rejected action types

const fetchUsers = createAsyncThunk('user/fetchUsers', () => {
  return axios
    .get('https://jsonplaceholders.typicode.com/users')
    .then(response => response.data.map(user => user.id))
})

const userSlice = createSlice({
  name: 'user',
  initialState,
  //reducer listening for the promise lifecycle action types(these become the sync action generators)
  extraReducers: builder => {
    builder.addCase(fetchUsers.pending, state => {
      state.loading = true
    })
    builder.addCase(fetchUsers.fulfilled, (state, action) => {
      state.loading = false
      state.users = action.payload
      state.error = ''
    })
    builder.addCase(fetchUsers.rejected, (state, action) => {
      state.loading = false
      state.users = []
      state.error = action.error.message
    })
  }
})

module.exports = userSlice.reducer
module.exports.fetchUsers = fetchUsers
